### ISSUE TITLE
Use camera (Waveshare) under Bullseye (64) with OpenCV

### ISSUE THREAD

**Issue by Petros626** [Qengineering/Libcamera-OpenCV-RPi-Bullseye-64OS#5]
Hey guys,

i have done some research and tried a lot, but somehow it doesn't seem to be possible to get a proper function with `libcamera` under _OpenCV._ I have tested two workarounds successfully, but what about the current support for cameras in combination with _OpenCV._ Did you manage to get them working?

(related to this topic: https://github.com/opencv/opencv/issues/19527 , https://github.com/leswright1977/PySpectrometer/issues/27)

Thanks in advance

**Comment by Qengineering** [comment]
@Petros626 ,

I understand you are a Python programmer. In that case I would like to refer you to the [Picamera2](https://github.com/raspberrypi/picamera2) library. This is the standard library of the Raspberry Pi programmers that you should use if you want to use a camera in Bullseye 64 OS.
See also the [documentation](https://datasheets.raspberrypi.com/camera/picamera2-manual.pdf).

**Comment by Petros626** [comment]
Okay thanks, maybe it's better placed there.
